# -*- coding: utf-8 -*-
"""CIFAR-10 Image Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ty11zYS6KlsqEoRrAlsU_8rSygX-R2VP

# Install Required Libraries
"""

# Install required packages (if not already available)
!pip install -q tensorflow matplotlib seaborn scikit-learn pandas numpy pillow

"""# Import Required Libraries"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Dense,
    Flatten,
    Dropout,
    BatchNormalization
)
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix
)

import random

print("TensorFlow Version:", tf.__version__)

"""# Load CIFAR-10 Dataset"""

# Load dataset
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

print("Training Images :", X_train.shape)
print("Training Labels :", y_train.shape)

print("Testing Images :", X_test.shape)
print("Testing Labels :", y_test.shape)

"""# Define Class Names"""

class_names = [
    'Airplane',
    'Automobile',
    'Bird',
    'Cat',
    'Deer',
    'Dog',
    'Frog',
    'Horse',
    'Ship',
    'Truck'
]

print(class_names)

"""# Display Sample Images"""

plt.figure(figsize=(12,6))

for i in range(10):
    plt.subplot(2,5,i+1)
    plt.imshow(X_train[i])
    plt.title(class_names[y_train[i][0]])
    plt.axis("off")

plt.tight_layout()
plt.show()

"""# Normalize Images"""

# Convert to float32
X_train = X_train.astype("float32")
X_test = X_test.astype("float32")

# Normalize pixel values to [0, 1]
X_train = X_train / 255.0
X_test = X_test / 255.0

print("Normalization Completed.")

"""# One-Hot Encode Labels"""

y_train_cat = to_categorical(y_train, 10)
y_test_cat = to_categorical(y_test, 10)

print(y_train_cat.shape)
print(y_test_cat.shape)

"""# Create Data Augmentation"""

train_generator = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.10,
    height_shift_range=0.10,
    horizontal_flip=True,
    zoom_range=0.10
)

train_generator.fit(X_train)

print("Data Augmentation Ready.")

"""# Build an Improved CNN Model

This CNN uses Batch Normalization and Dropout to improve accuracy and reduce overfitting.
"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Dense,
    Flatten,
    Dropout,
    BatchNormalization
)

model = Sequential([

    # Block 1
    Conv2D(32, (3,3), activation='relu', padding='same',
           input_shape=(32,32,3)),
    BatchNormalization(),
    Conv2D(32, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.25),

    # Block 2
    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    Conv2D(64, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.30),

    # Block 3
    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    Conv2D(128, (3,3), activation='relu', padding='same'),
    BatchNormalization(),
    MaxPooling2D(pool_size=(2,2)),
    Dropout(0.40),

    # Fully Connected Layer
    Flatten(),

    Dense(512, activation='relu'),
    BatchNormalization(),
    Dropout(0.50),

    Dense(10, activation='softmax')
])

model.summary()

"""# Compile the Model"""

from tensorflow.keras.optimizers import Adam

optimizer = Adam(learning_rate=0.001)

model.compile(
    optimizer=optimizer,
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print("Model Compiled Successfully!")

"""# Define Callbacks

These callbacks improve training by:

*   Saving the best model
*   Stopping early if validation loss doesn't improve
*   Reducing the learning rate automatically





"""

from tensorflow.keras.callbacks import (
    EarlyStopping,
    ReduceLROnPlateau,
    ModelCheckpoint
)

checkpoint = ModelCheckpoint(
    "best_model.keras",
    monitor='val_accuracy',
    save_best_only=True,
    verbose=1
)

earlystop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.5,
    patience=5,
    min_lr=1e-6,
    verbose=1
)

callbacks = [
    checkpoint,
    earlystop,
    reduce_lr
]

"""# Train the Model"""

history = model.fit(
    train_generator.flow(
        X_train,
        y_train_cat,
        batch_size=64
    ),
    epochs=15,
    validation_data=(X_test, y_test_cat),
    callbacks=callbacks,
    verbose=1
)

"""

# Save the Final Model
"""

model.save("cifar10_cnn_model.keras")

print("Model Saved Successfully!")

"""# Load the Best Mode"""

from tensorflow.keras.models import load_model

best_model = load_model("best_model.keras")

print("Best model loaded successfully!")

"""# Plot Training & Validation Accuracy"""

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.title("Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)

plt.show()

"""# Plot Training & Validation Loss"""

plt.figure(figsize=(10,5))

plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')

plt.title("Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)

plt.show()

"""# Evaluate Model on Test Dataset"""

test_loss, test_accuracy = best_model.evaluate(
    X_test,
    y_test_cat,
    verbose=1
)

print("="*40)
print(f"Test Loss     : {test_loss:.4f}")
print(f"Test Accuracy : {test_accuracy*100:.2f}%")
print("="*40)

"""# Predict Test Images"""

y_pred_prob = best_model.predict(X_test)

y_pred = y_pred_prob.argmax(axis=1)

y_true = y_test.flatten()

print("Prediction Completed!")

"""# Classification Report"""

from sklearn.metrics import classification_report

print(classification_report(
    y_true,
    y_pred,
    target_names=class_names
))

"""# Confusion Matrix"""

from sklearn.metrics import confusion_matrix
import seaborn as sns

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(10,8))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names
)

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")

plt.show()

"""# Display Random Predictions"""

import random

plt.figure(figsize=(15,10))

for i in range(15):

    index = random.randint(0, len(X_test)-1)

    plt.subplot(3,5,i+1)

    plt.imshow(X_test[index])

    predicted = class_names[y_pred[index]]

    actual = class_names[y_true[index]]

    color = "green" if predicted == actual else "red"

    plt.title(
        f"P:{predicted}\nA:{actual}",
        color=color,
        fontsize=10
    )

    plt.axis("off")

plt.tight_layout()
plt.show()

"""# Predict a Single Test Image"""

index = 50

image = X_test[index]

prediction = best_model.predict(
    np.expand_dims(image, axis=0)
)

predicted_class = class_names[np.argmax(prediction)]

actual_class = class_names[y_true[index]]

plt.figure(figsize=(4,4))
plt.imshow(image)
plt.axis("off")

plt.title(
    f"Predicted : {predicted_class}\nActual : {actual_class}"
)

plt.show()

"""# Save Accuracy and Loss Values"""

results = {
    "Training Accuracy": max(history.history["accuracy"]),
    "Validation Accuracy": max(history.history["val_accuracy"]),
    "Training Loss": min(history.history["loss"]),
    "Validation Loss": min(history.history["val_loss"]),
    "Test Accuracy": test_accuracy,
    "Test Loss": test_loss
}

for key, value in results.items():
    print(f"{key}: {value:.4f}")

"""# Save Results to CSV"""

import pandas as pd

results_df = pd.DataFrame([results])

results_df.to_csv("performance_results.csv", index=False)

print("Results saved successfully!")

"""# Upload Your Own Image"""

from google.colab import files

uploaded = files.upload()

"""# Predict a Custom Image"""

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# Replace with your uploaded image name
image_path = "1000105005 (1) (1).jpg"

img = image.load_img(image_path, target_size=(32,32))
img_array = image.img_to_array(img)
img_array = img_array / 255.0
img_array = np.expand_dims(img_array, axis=0)

prediction = best_model.predict(img_array)

predicted_class = class_names[np.argmax(prediction)]
confidence = np.max(prediction) * 100

plt.imshow(image.load_img(image_path))
plt.axis("off")
plt.title(f"{predicted_class} ({confidence:.2f}%)")
plt.show()

print("Prediction :", predicted_class)
print("Confidence :", confidence)

"""# Download the Trained Model"""

from google.colab import files

files.download("best_model.keras")

"""# Streamlit Web Application"""

!pip install -q streamlit

import streamlit as st
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model

model = load_model("best_model.keras")

class_names = [
    "Airplane",
    "Automobile",
    "Bird",
    "Cat",
    "Deer",
    "Dog",
    "Frog",
    "Horse",
    "Ship",
    "Truck"
]

st.title("CIFAR-10 Image Classifier")

uploaded_file = st.file_uploader(
    "Upload an Image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:

    img = Image.open(uploaded_file)

    st.image(img, caption="Uploaded Image", use_container_width=True)

    img = img.resize((32,32))

    img = np.array(img)

    if img.shape[-1] == 4:
        img = img[:,:,:3]

    img = img.astype("float32") / 255.0

    img = np.expand_dims(img, axis=0)

    prediction = model.predict(img)

    predicted = class_names[np.argmax(prediction)]

    confidence = np.max(prediction) * 100

    st.success(f"Prediction: {predicted}")

    st.write(f"Confidence: {confidence:.2f}%")